import React, { lazy } from 'react';

export const pages = {
  AppLauncher: lazy(() => import('./AppLauncher.jsx')),
  Dashboard: lazy(() => import('./Dashboard.jsx')),
  Chat: lazy(() => import('./Chat.jsx')),
  Feed: lazy(() => import('./Feed.jsx')),
  Wallet: lazy(() => import('./Wallet.jsx')),
  Profile: lazy(() => import('./Profile.jsx')),
  FerretFiles: lazy(() => import('./FerretFiles.jsx')),
  FerretNotes: lazy(() => import('./FerretNotes.jsx')),
  FerretTasks: lazy(() => import('./FerretTasks.jsx')),
  FerretCalendar: lazy(() => import('./FerretCalendar.jsx')),
  FerretMail: lazy(() => import('./FerretMail.jsx')),
  FerretTerminal: lazy(() => import('./FerretTerminal.jsx')),
  FerretGallery: lazy(() => import('./FerretGallery.jsx')),
  FerretMedia: lazy(() => import('./FerretMedia.jsx')),
  FerretWeather: lazy(() => import('./FerretWeather.jsx')),
  FerretFitness: lazy(() => import('./FerretFitness.jsx')),
  FERCodeV2: lazy(() => import('./FERCodeV2.jsx')),
  MLDashboard: lazy(() => import('./MLDashboard.jsx')),
  PredictiveDashboard: lazy(() => import('./PredictiveDashboard.jsx')),
  OptimizationDashboard: lazy(() => import('./OptimizationDashboard.jsx')),
  PhysicsDashboard: lazy(() => import('./PhysicsDashboard.jsx')),
  ValidationDashboard: lazy(() => import('./ValidationDashboard.jsx')),
  AIFInspector: lazy(() => import('./AIFInspector.jsx')),
  MeshNetwork: lazy(() => import('./MeshNetwork.jsx')),
  AifMarketplace: lazy(() => import('./AifMarketplace.jsx')),
};
